services:
  postgres:
    image: postgres:17
    container_name: espritlivre-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=el-dev-db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - espritlivre_postgres_data:/var/lib/postgresql/data
    networks:
      - espritlivre-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    container_name: espritlivre-keycloak
    command: 'start-dev --import-realm'
    volumes:
      - ./src/main/docker/realm-config:/opt/keycloak/data/import
      - ./src/main/docker/realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
    ports:
      - "9080:9080"
      - "9443:9443"
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 10s
    networks:
      - espritlivre-network

volumes:
  espritlivre_postgres_data:
    name: espritlivre_postgres_data

networks:
  espritlivre-network:
